### ISSUE TITLE
Mario and luigi superstar saga scaling glitch

### ISSUE THREAD

**Issue by old3dshax** [Gericom/GBARunner2#133]
![1590200883091238085801](https://user-images.githubusercontent.com/65797488/82719779-3f931f80-9c73-11ea-87cb-61e84d1b4aa5.jpg)
Sorry for bad quality old phone 
Also pls fix thx:)

**Comment by zenseii** [comment]
This is called the twlbg bug and is due to how Nintendo developed their DS-side support of the 3DS (gbarunner2 runs in the ds mode, called TWL_firm, of the 3DS). This can even happen when playing normal retail DS cartridges afaik. However, the developer Gericom is looking at ways he can reduce this from happening. The only solution right now is to restart GBARunner2 and try to avoid the thing that causes it.

**Comment by old3dshax** [comment]
I've downloaded an older version it doesn't seem to be happening, but I'll keep this open in case it happens again

**Comment by Gericom** [comment]
That's because older versions of gbarunner do not adjust the framerate

**Comment by michelemassa5599** [comment]
> That's because older versions of gbarunner do not adjust the framerate

Just use NSUI Injects, then mGBA3DS instead.
