### ISSUE TITLE
Sonic advance 1 and 2 black screen coming and closing view 

### ISSUE THREAD

**Issue by Algamerthetruealbanian** [Gericom/GBARunner2#134]
i dont know if i made any sense for this 
but those 2 games have sound but cant be played due to black stripes coming and filling the screen 
if this is an alredy documented isuse im sorry to repeat it

**Comment by zenseii** [comment]
Yes it is already known. To play them on the latest build you can try to apply a patch found for it in its entry on the compatibility list:
[https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List](https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List)
If not the latest builds of the wifi_link branch play these games as well:
[https://github.com/Gericom/GBARunner2/releases/tag/v20200217-194452_0b8bbe3](https://github.com/Gericom/GBARunner2/releases/tag/v20200217-194452_0b8bbe3)

**Comment by Algamerthetruealbanian** [comment]
ok i guess i will wait for the latest build to test it 

though why it a issue with gbarunner  
just asking?

**Comment by Algamerthetruealbanian** [comment]
after removing the intro on the rom 
both rom usa just crash with jumped to incorrect header

**Comment by zenseii** [comment]
Removing the intro does not solve the problem. The reason it softlocks is because it checks the linking capability and since that is only implemented in the wifi_link branch it will only work on that. A patch, which as I said is found in the links I gave you, will remove this check afaik.

Not sure if waiting for next release is a good idea because I don't think wifi_link branch will be merged into it immediately. You should either apply the patch or use the wifi link release.

**Comment by Algamerthetruealbanian** [comment]
thnx

**Comment by qahellokitty5947** [comment]
> Removing the intro does not solve the problem. The reason it softlocks is because it checks the linking capability and since that is only implemented in the wifi_link branch it will only work on that. A patch, which as I said is found in the links I gave you, will remove this check afaik.
> 
> Not sure if waiting for next release is a good idea because I don't think wifi_link branch will be merged into it immediately. You should either apply the patch or use the wifi link release.

you will be used to work on gpsp kai 3.5 mod to prevent damage to your game!!!!
