### ISSUE TITLE
Weird issues with Harry Potter Collection

### ISSUE THREAD

**Issue by G9-Dev** [Gericom/GBARunner2#194]
Harry Potter 1 works fine, Harry Potter 2 doesn't even boot, and Harry Potter 3 doesn't save...
Please help, i want to run Harry Potter 2, i worked on mGba, idk why its not working...

NB: i tested every rom individually, same results

**Comment by G9-Dev** [comment]
I fixed it by dumping a BIOS, at least for Harry Potter 2.
For everyone who have issues with a game : dump a bios !
And sorry but I can't close this issue, can you close it ... 
ÉDIT oh well I've found it

**Comment by G9-Dev** [comment]
Now the game freezes after dialogue of new game ;( 
Please help

**Comment by zenseii** [comment]
Not sure what version and what setup you're using since you haven't specified it, but reading up on the wiki should answer most of your problems:
https://wiki.gbatemp.net/wiki/GBARunner2

If you're not getting the same results as the wiki for the roms you are testing then make sure you are running the same build as reported used for the testing on the wiki.

**Comment by G9-Dev** [comment]
> Not sure what version and what setup you're using since you haven't specified it, but reading up on the wiki should answer most of your problems:
> 
> https://wiki.gbatemp.net/wiki/GBARunner2
> 
> 
> 
> If you're not getting the same results as the wiki for the roms you are testing then make sure you are running the same build as reported used for the testing on the wiki.


I've fixed it by disabling wram boost. Well now saving doesn't work. But it's the 3 in 1 Tim's fault. I've downloaded single rom and it worked. Thanks !
