### ISSUE TITLE
How do I compile this for 3ds?

### ISSUE THREAD

**Issue by chowder3907** [Gericom/GBARunner2#259]
I've managed to successfully compile this in the main folder, arm7, and arm9 folder. The resulting `GBARunner2.nds` does _not_ run on the 3ds. What do I need to do to compile the arm7 dldi version? I'm trying to compile the wifi_link branch. I am on Linux.

**Comment by Epicpkmn11** [comment]
Run:
```bash
make all ARM7_DLDI=1 USE_3DS_32MB=1
```

([azure-pipelines.yml:61](https://github.com/Gericom/GBARunner2/blob/wifi_link/azure-pipelines.yml#L61))

Though while it may compile, GBARunner2 requires a very specific toolchain setup to actually run currently so I don't think you'll actually get a working build from that. (unless I'm mistaken, which could be the case, I haven't been able to get a working build myself though)

If you didn't know, there's a release with an auto build from the wifi_link branch fyi: https://github.com/Gericom/GBARunner2/releases/tag/v20200217-194452_0b8bbe3

Edit: Oh, since you mention you're on linux you'll need to remove all the `.exe`s from the Makefiles fyi, see #187 for what exactly

**Comment by chowder3907** [comment]
> ```shell
> ```shell
> make all ARM7_DLDI=1 USE_3DS_32MB=1
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

This command worked perfectly after running `make clean`
It opens the file now but gives me a black screen, I don't know if that's because I did something wrong or because it's got a bug or two. Thanks!
